# Copyright (c) 2016, Linaro Limited
# All rights reserved.
# SPDX-License-Identifier:     BSD-3-Clause
#
# Please update xxxx for your coverity token and notification email if required
# pushing to github/master will run make check
# pushing to github/coverity_scan will also launch a static analysis
# See https://scan.coverity.com/travis_ci

env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    - secure: "rCtRCqiu62AjLuM3ilt91LbRSJs7ScKpjB/cvX3PPlZLr2yPSQ7tsWQx4v5t7Nrvz/taO6TVLI4fcvHzy8xCg7D2DMXZ2ML6sFy/QoHehRM+Tnn/N+wVhvRapu30bv90a3ChYyvywJbXmm6vZhr3EBPkmrKL16s7tW+3e2FAAU1ZCd08HhR3wYkBvwfVkgzFNVcJ7PtIQMQZt2289yLx2AQbkxZI312ePZqgnJJEFC07eAt5iWN9yjl0gOddAT/UPGDeATU9uQd2wJuAItCGQfAKkxa1yQ3jycE5ZCelTBFq+t4OXMCQ6hD3P81XzbzdIfGcRHBpSzoJydxY7poUJwlkdZ6eNKQW9I1LBhUqxsAMFMTFsQ/iPiihcwptWiZK7NgqBYBJhj7FSblvO0F+Hs2Qa4qtMrNZDJneVs6gHFaFjgy5T4f2JedyQcMOz3WrBqGLvEP4vQW2tsIZ1N9AjDfzO9SwO7b3HfZj9hxgrZ/kHQ7xS1gMBJgAx7KTV2YQKiNflM2ErlEi97KDZGBSu4Bl+APJvZpIPQMQ/V3FuIjYin0h5maJnyjDFPfITocFqPp2z6kQSw17WtuFDwqIasdrLStj4Xo7Awe5dc3k7DHCwyA70z5hobudTahyZwXm6IU/zHvkzvNOB5/fWaMbQDEpXXtQgrbY2VIPZAPB1xY="

language: c
compiler: clang
sudo: required

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install automake autoconf libtool libssl-dev graphviz mscgen doxygen
        - sudo apt-get install libpcap-dev linux-headers-`uname -r`
        - gem install asciidoctor

#       Install cunit for the validation tests because distro version is too old and fails C99 compile
        - export CUNIT_VERSION=2.1-3
        - curl -sSOL http://sourceforge.net/projects/cunit/files/CUnit/${CUNIT_VERSION}/CUnit-${CUNIT_VERSION}.tar.bz2
        - tar -jxf *.bz2
        - cd CUnit*
        - ./bootstrap
        - ./configure --enable-debug --enable-automated --enable-basic --enable-console --enable-examples --enable-test
        - make
        - sudo make install
        - cd ..
        - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
#	DPDK pktio
        - TARGET=${TARGET:-"x86_64-native-linuxapp-gcc"}
        - git -c advice.detachedHead=false clone -q --depth=1 --single-branch --branch=v16.07 http://dpdk.org/git/dpdk dpdk
        - pushd dpdk
        - git log --oneline --decorate
        - make config T=${TARGET} O=${TARGET}
        - pushd ${TARGET}
        - sed -ri 's,(CONFIG_RTE_LIBRTE_PMD_PCAP=).*,\1y,' .config
        - popd
        - make install T=${TARGET} EXTRA_CFLAGS="-fPIC" > /dev/null
        - popd

script:

        - ./bootstrap
        - ./configure --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-dpdk-path=`pwd`/dpdk/${TARGET}
        - make check
        - git clean -f -d -x && rm -rf dpdk
        - ./bootstrap
        - ./configure
        - make doxygen-doc
        - make distcheck

addons:
    coverity_scan:
        project:
            name: "$TRAVIS_REPO_SLUG"
        notification_email: xxxx
        build_command_prepend: "./bootstrap && ./configure --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example"
        build_command:   "make"
        branch_pattern: coverity_scan
